In [1]:
from benchmark import data

ModuleNotFoundError: No module named 'benchmark'

In [2]:
gc = data.GaussianClusters()

In [10]:
x = gc.x.numpy()
y = gc.y.numpy()

In [21]:
u = (x + y)
u.shape

(3750, 20)

In [6]:
import pandas as pd

In [24]:
ds = pd.DataFrame(x)

In [25]:
ds["y"] = y

In [26]:
ds

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,y
0,13.586031,3.972751,-2.337117,-2.770802,0.251289,-5.567671,-0.568681,4.499282,0.616844,-0.284877,...,3.030927,-3.116938,0.888053,-0.882650,1.378443,1.234614,-0.457572,-4.139137,0.995677,0.0
1,12.932649,3.829310,-2.165784,1.169720,-3.041421,-4.835941,2.528395,5.491048,-0.839876,1.340929,...,3.806133,-1.182684,-0.696789,1.628961,1.605709,-7.306755,-4.016372,-5.170349,-3.444168,0.0
2,-16.951555,0.311035,0.689115,-1.702783,-2.134131,5.413485,-2.862652,-2.712176,1.556504,4.544737,...,-4.337011,3.372343,3.205052,-1.982790,0.515979,1.874192,-0.519720,2.132056,-3.286698,0.0
3,-12.981864,-4.480978,0.334676,3.167495,-2.536851,-0.973182,-2.709302,3.322027,-1.903642,0.972262,...,-2.002513,-2.014266,-2.509826,-2.692758,-2.151201,-10.958467,1.817824,2.196800,-2.171937,1.0
4,1.461625,-0.348152,1.952048,1.517612,-2.125287,-0.474028,3.174500,1.278505,2.060668,3.904735,...,-1.148850,-2.164483,-0.294810,-0.250037,0.195989,-3.575630,-3.201764,-2.288641,-0.201474,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3745,5.316578,0.831926,0.845810,0.584296,3.379342,1.338691,3.335283,-4.443793,2.501598,-3.180199,...,-0.354096,0.293438,1.289125,-1.658662,-1.576063,3.305887,-0.702959,-1.113589,0.937654,1.0
3746,-2.038742,2.791231,-0.992095,1.998607,4.518058,-2.584432,-5.004947,0.995714,1.449852,-2.281573,...,1.076180,0.907720,-0.920361,5.048073,-4.305316,2.258345,0.543350,0.476815,-4.509487,0.0
3747,-5.743013,-5.649454,-5.543440,-3.354643,1.444860,-1.445921,4.310588,1.620499,1.846318,4.931510,...,0.960267,-3.159628,0.358380,-4.440716,2.546718,-14.245929,5.197439,0.307537,-0.393424,0.0
3748,-8.923874,-1.548572,2.261862,4.665462,-4.631278,3.282693,-0.702392,2.361859,0.837625,-3.555330,...,-1.491174,1.499688,0.478697,2.440314,1.574763,-5.638287,2.070012,2.787209,-7.351460,1.0
3749,-6.331364,-1.051420,-1.955136,-0.496789,4.574629,-0.046724,-4.500669,0.900243,0.967319,0.384378,...,1.550271,-0.139205,-2.811175,4.713279,-2.725734,-1.284089,2.318490,-1.180484,-4.658010,0.0

In [30]:
import tempfile
tf = tempfile.mktemp()

In [36]:
with open(tf, "w") as fp:
    csv = ds.to_csv(index=False)
    fp.write(csv)

In [38]:
csv[:1000]

'0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,y\n13.586031,3.9727514,-2.3371167,-2.770802,0.25128856,-5.567671,-0.5686806,4.499282,0.6168443,-0.28487673,2.0223892,3.0309267,-3.1169379,0.88805336,-0.88265,1.3784435,1.234614,-0.4575715,-4.139137,0.99567723,0.0\n12.932649,3.8293097,-2.1657836,1.1697196,-3.0414207,-4.835941,2.5283952,5.491048,-0.8398759,1.3409292,3.64833,3.8061326,-1.1826837,-0.6967887,1.6289612,1.6057087,-7.3067546,-4.016372,-5.170349,-3.4441679,0.0\n-16.951555,0.31103542,0.68911535,-1.7027825,-2.1341314,5.413485,-2.8626523,-2.7121756,1.5565044,4.5447373,-1.2690997,-4.3370113,3.372343,3.2050521,-1.9827902,0.5159789,1.8741915,-0.5197202,2.1320558,-3.2866979,0.0\n-12.981864,-4.480978,0.33467618,3.1674948,-2.5368512,-0.97318214,-2.7093022,3.3220267,-1.903642,0.97226244,-2.321154,-2.0025134,-2.0142663,-2.5098262,-2.692758,-2.1512012,-10.9584675,1.8178244,2.1967995,-2.1719365,1.0\n1.4616249,-0.3481517,1.9520477,1.5176122,-2.1252873,-0.47402847,3.1744998,1.278505,2.0606682,3.904'

In [39]:
loaded = pd.read_csv(tf)

In [40]:
loaded.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,y
0,13.586031,3.972751,-2.337117,-2.770802,0.251289,-5.567671,-0.568681,4.499282,0.616844,-0.284877,...,3.030927,-3.116938,0.888053,-0.882650,1.378443,1.234614,-0.457572,-4.139137,0.995677,0.0
1,12.932649,3.829310,-2.165784,1.169720,-3.041421,-4.835941,2.528395,5.491048,-0.839876,1.340929,...,3.806133,-1.182684,-0.696789,1.628961,1.605709,-7.306755,-4.016372,-5.170349,-3.444168,0.0
2,-16.951555,0.311035,0.689115,-1.702783,-2.134131,5.413485,-2.862652,-2.712176,1.556504,4.544737,...,-4.337011,3.372343,3.205052,-1.982790,0.515979,1.874192,-0.519720,2.132056,-3.286698,0.0
3,-12.981864,-4.480978,0.334676,3.167495,-2.536851,-0.973182,-2.709302,3.322027,-1.903642,0.972262,...,-2.002513,-2.014266,-2.509826,-2.692758,-2.151201,-10.958467,1.817824,2.196800,-2.171937,1.0
4,1.461625,-0.348152,1.952048,1.517612,-2.125287,-0.474028,3.174500,1.278505,2.060668,3.904735,...,-1.148850,-2.164483,-0.294810,-0.250037,0.195989,-3.575630,-3.201764,-2.288641,-0.201474,0.0

In [64]:
loaded.iloc[:,:-1]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,13.586031,3.972751,-2.337117,-2.770802,0.251289,-5.567671,-0.568681,4.499282,0.616844,-0.284877,2.022389,3.030927,-3.116938,0.888053,-0.882650,1.378443,1.234614,-0.457572,-4.139137,0.995677
1,12.932649,3.829310,-2.165784,1.169720,-3.041421,-4.835941,2.528395,5.491048,-0.839876,1.340929,3.648330,3.806133,-1.182684,-0.696789,1.628961,1.605709,-7.306755,-4.016372,-5.170349,-3.444168
2,-16.951555,0.311035,0.689115,-1.702783,-2.134131,5.413485,-2.862652,-2.712176,1.556504,4.544737,-1.269100,-4.337011,3.372343,3.205052,-1.982790,0.515979,1.874192,-0.519720,2.132056,-3.286698
3,-12.981864,-4.480978,0.334676,3.167495,-2.536851,-0.973182,-2.709302,3.322027,-1.903642,0.972262,-2.321154,-2.002513,-2.014266,-2.509826,-2.692758,-2.151201,-10.958467,1.817824,2.196800,-2.171937
4,1.461625,-0.348152,1.952048,1.517612,-2.125287,-0.474028,3.174500,1.278505,2.060668,3.904735,2.907286,-1.148850,-2.164483,-0.294810,-0.250037,0.195989,-3.575630,-3.201764,-2.288641,-0.201474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3745,5.316578,0.831926,0.845810,0.584296,3.379342,1.338691,3.335283,-4.443793,2.501598,-3.180199,1.842377,-0.354096,0.293438,1.289125,-1.658662,-1.576063,3.305887,-0.702959,-1.113589,0.937654
3746,-2.038742,2.791231,-0.992095,1.998607,4.518058,-2.584432,-5.004947,0.995714,1.449852,-2.281573,-2.650164,1.076180,0.907720,-0.920361,5.048073,-4.305316,2.258345,0.543350,0.476815,-4.509487
3747,-5.743013,-5.649454,-5.543440,-3.354643,1.444860,-1.445921,4.310588,1.620499,1.846318,4.931510,-0.204789,0.960267,-3.159628,0.358380,-4.440716,2.546718,-14.245929,5.197439,0.307537,-0.393424
3748,-8.923874,-1.548572,2.261862,4.665463,-4.631278,3.282693,-0.702392,2.361859,0.837625,-3.555330,-0.819588,-1.491174,1.499688,0.478697,2.440314,1.574763,-5.638287,2.070012,2.787209,-7.351460
3749,-6.331364,-1.051421,-1.955136,-0.496789,4.574629,-0.046724,-4.500669,0.900243,0.967319,0.384378,-0.635614,1.550271,-0.139205,-2.811175,4.713279,-2.725735,-1.284089,2.318490,-1.180484,-4.658010

In [67]:
loaded.iloc[:,-1:]

        y
0     0.0
1     0.0
2     0.0
3     1.0
4     0.0
...   ...
3745  1.0
3746  0.0
3747  0.0
3748  1.0
3749  0.0

[3750 rows x 1 columns]

In [52]:
x_loaded = (loaded.iloc[:,:-1]).to_numpy(dtype="float32")

In [53]:
x_loaded

array([[ 13.586031  ,   3.9727514 ,  -2.3371167 , ...,  -0.4575715 ,
         -4.139137  ,   0.99567723],
       [ 12.932649  ,   3.8293097 ,  -2.1657836 , ...,  -4.016372  ,
         -5.170349  ,  -3.4441679 ],
       [-16.951555  ,   0.31103542,   0.68911535, ...,  -0.5197202 ,
          2.1320558 ,  -3.2866979 ],
       ...,
       [ -5.743013  ,  -5.6494536 ,  -5.54344   , ...,   5.1974387 ,
          0.30753723,  -0.39342442],
       [ -8.923874  ,  -1.5485717 ,   2.2618616 , ...,   2.0700123 ,
          2.7872093 ,  -7.35146   ],
       [ -6.331364  ,  -1.0514205 ,  -1.9551356 , ...,   2.3184898 ,
         -1.1804838 ,  -4.6580095 ]], dtype=float32)

In [57]:
x[10,3]=2

In [58]:
(x==x_loaded).all()

False

In [68]:
y_loaded = (loaded.iloc[:,-1:]).to_numpy(dtype="float32")
y_loaded

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]], dtype=float32)

In [69]:
(y_loaded == y).all()

True